In [ ]:
'''Q1: Consider the following sensor readings:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
A sensor has an average measurement error of +2°C.
Perform the following without using a for loop:
a. Add 2°C to every reading using vectorization.
b. Convert all temperatures from Celsius to Fahrenheit.
c. Identify all readings greater than 32°C using Boolean indexing.
d. Count how many readings exceed 32°C.
e. Explain how vectorization and Boolean indexing can make data processing more efficient.'''


In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2
fahrenheit = (9/5) * corrected_temperature + 32
greater_than_32 = corrected_temperature[corrected_temperature > 32]
count_greater_than_32 = np.sum(corrected_temperature > 32)

print("Corrected temperatures:", corrected_temperature)
print("Temperatures in Fahrenheit:", fahrenheit)
print("Readings greater than 32°C:", greater_than_32)
print("Count of readings greater than 32°C:", count_greater_than_32)

print("\nExplanation:")
print("Vectorization applies an operation to the complete NumPy array at once, avoiding explicit loops.")
print("Boolean indexing directly selects values satisfying a condition, making array filtering concise and efficient.")


Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Count of readings greater than 32°C: 5

Explanation:
Vectorization applies an operation to the complete NumPy array at once, avoiding explicit loops.
Boolean indexing directly selects values satisfying a condition, making array filtering concise and efficient.


In [ ]:
'''Q2: The following matrix represents the number of daily steps recorded by four users over three days:
steps = np.array([
[5000, 6200, 7100],
[8000, 7500, 9000],
[4500, 5100, 4800],
[9000, 8500, 9500]])
Perform the following:
a. Calculate the total steps recorded.
b. Calculate the mean number of steps.
c. Find the maximum and minimum values.
d. Calculate the total steps for each day using axis=0.
e. Calculate the total steps for each user using axis=1.
f. Find the user/day position containing the maximum number of steps using argmax().'''


In [2]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

total_steps = np.sum(steps)
mean_steps = np.mean(steps)
maximum = np.max(steps)
minimum = np.min(steps)
daily_total = np.sum(steps, axis=0)
user_total = np.sum(steps, axis=1)
max_position = np.unravel_index(np.argmax(steps), steps.shape)

print("Total steps:", total_steps)
print("Mean steps:", mean_steps)
print("Maximum steps:", maximum)
print("Minimum steps:", minimum)
print("Total steps for each day:", daily_total)
print("Total steps for each user:", user_total)
print("Maximum value position (user, day):", max_position)
print("Maximum value:", steps[max_position])


Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Maximum value position (user, day): (np.int64(3), np.int64(2))
Maximum value: 9500


In [ ]:
'''Q3: Write a Python program using NumPy to perform the following operations:
a. Create the array [1, 2, 3, 4, 5, 6].
b. Create a slice containing elements from index 1 to 4 and store it in subset.
c. Modify the first element of subset to 999 and display both original and subset.
d. Create another slice from original using .copy(). Modify its first element to 500 and display original and copied array.
e. Create an array containing numbers from 1 to 12 using np.arange() and reshape it into a 3 × 4 matrix.
f. Extract first row, last row, second column, and elements from rows 1–2 and columns 2–3.
g. Create flattened versions using flatten() and ravel().
h. Modify an element in ravel() and observe whether original is affected.
i. Modify an element in flatten() and observe whether original is affected.
j. Display shape, ndim, size, and dtype of the original 3 × 4 matrix.'''


In [3]:
original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]
subset[0] = 999

print("Original after modifying subset:", original)
print("Subset:", subset)

copied = original[1:5].copy()
copied[0] = 500

print("Original after modifying copied array:", original)
print("Copied array:", copied)

matrix = np.arange(1, 13).reshape(3, 4)

print("\n3 x 4 matrix:")
print(matrix)

print("\nFirst row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2 and columns 2-3:")
print(matrix[1:3, 2:4])

flattened = matrix.flatten()
raveled = matrix.ravel()

print("\nFlatten:", flattened)
print("Ravel:", raveled)

raveled[0] = 100
print("\nAfter modifying ravel:")
print("Ravel:", raveled)
print("Original matrix:")
print(matrix)

flattened[1] = 200
print("\nAfter modifying flatten:")
print("Flatten:", flattened)
print("Original matrix:")
print(matrix)

print("\nShape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)


Original after modifying subset: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original after modifying copied array: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]

3 x 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]

Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel:
Ravel: [100   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

After modifying flatten:
Flatten: [  1 200   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [ ]:
'''Q4: A simple cognitive-assistive system wants to predict a user's assistance score based on:
Sleep hours, Activity level, Stress level.
X = np.array([
[6, 70, 3],
[5, 50, 6],
[8, 80, 2],
[4, 30, 8]
])
y = np.array([40, 65, 30, 85])
Perform:
a. Display the shape and dimensions of X.
b. Calculate X.T and explain what the transpose represents.
c. Calculate X.T @ X.
d. Calculate the matrix inverse using np.linalg.inv().
e. Implement beta = (X.T X)^-1 X.T y using NumPy.
f. Explain what the resulting coefficients represent.
g. For new_user = np.array([5, 40, 7]), obtain a predicted assistance score.'''


In [4]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

XT = X.T
print("\nX.T:")
print(XT)

print("\nTranspose explanation:")
print("Rows represent features and columns represent users after transposition.")

XTX = X.T @ X
print("\nX.T @ X:")
print(XTX)

XTX_inverse = np.linalg.inv(XTX)
print("\nInverse of X.T @ X:")
print(XTX_inverse)

beta = XTX_inverse @ X.T @ y
print("\nCoefficients (beta):", beta)

print("\nCoefficient explanation:")
print("The first coefficient represents the contribution associated with sleep hours.")
print("The second coefficient represents the contribution associated with activity level.")
print("The third coefficient represents the contribution associated with stress level.")

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta

print("\nNew user:", new_user)
print("Predicted assistance score:", predicted_score)


Shape of X: (4, 3)
Dimensions of X: 2

X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

Transpose explanation:
Rows represent features and columns represent users after transposition.

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

Coefficients (beta): [-0.15921454  0.14083853 10.06302242]

Coefficient explanation:
The first coefficient represents the contribution associated with sleep hours.
The second coefficient represents the contribution associated with activity level.
The third coefficient represents the contribution associated with stress level.

New user: [ 5 40  7]
Predicted assistance score: 75.27862544779117
